title: Cooper Bedin
logo: /assets/img/pfp.jpg
banner: /assets/img/trans-banner.PNG
description: Ph.D. Student - UCSB Department of Linguistics
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
